@startuml
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
'!include <C4/C4_Context>
'!include <C4/C4_Container>
'!include <C4/Component>

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()

Container_Boundary(framework, "Android Framework") {
    Container(renderer, "Renderer", "C++ : hwui, skia", $descr="Rendering module of Application.")
    Container(composer, "Composer Client", "C++", $descr="Content Committer of Application.")
    Container(window, "Window", "C++")
}
System(server, "SurfaceFlinger", "Android Graphic Server.")
Container(layer, "Layer", "C++")

System_Ext(gpu, "GPU", "3D Component.")
System_Ext(compositor, "HWComposer", "2D Component.")

Lay_R(renderer, composer)
Lay_R(composer, server)
'Lay_R(gpu, compositor)

Rel_R(composer, server, "Request")
Rel_L(server, composer, "Respond")
Rel_D(renderer, window, "Uses")
Rel_D(composer, window, "Uses")
Rel_D(window, gpu, "Uses")
Rel_D(server, layer, "Uses")
Rel_D(layer, compositor, "Uses")

SHOW_LEGEND()

@enduml
